name: Prepare Database

on:
  push:
    branches:
      - deploy

jobs:
  "setup-database":
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove existing database
        run: npx ts-node remove_db.ts "mongodb://127.0.0.1:27017/my_library_db"

      - name: Insert sample data
        run: npx ts-node insert_sample_db.ts "mongodb://127.0.0.1:27017/my_library_db"
